# Globally configure features for all channels.
# It will be the default option for channels which do not specify the option
# You can use any of the options within global in a channel
global:
    # Send player commands to Slack
    send-commands: true
    # Send player chat messages to Slack
    send-chat: true
    # Send login and logout messages to Slack
    send-player: true
    # Send commands as console from Slack to your server
    send-console: false
    # Send the console log to Slack
    receive-console: false
    # Use permissions to hide players from Slack (very small performance drop)
    use-perms: false
    # Check for commands to hide commands from Slack (small performance drop)
    use-blacklist: false
    # Commands that will not be sent to Slack
    blacklist:
        - /login
        - /register
# Configure individual message sources / Slack channels
channels:
    # The name of the channel
    default:
        # The incoming webhook (required for default)
        incoming-webhook: ''
        # The outgoing webhook key (required when receiving Slack messages)
        outgoing-webhook-key: ''
        # Port being used for the local webservice. If you add the ip to slack it should be
        outgoing-webhook-port: 8080

        text-formating: "[slack]<%s> %s"

        # What sources should be classified for handling for this channel
        # When using Bukkit, the default source type is a world. Example:
        # source: world
        # You may also name multiple worlds. Example:
        # source:
        #   - world1
        #   - world2
        # When using Bungee, the default source type is a server. Example:
        # source: server
        # You may also name multiple servers. Example:
        # source:
        #   - server1
        #   - server2
        # source: all means that all sources will be collected into the channel
        source: all
# The config version for internal use by the config updater.
config-version: 2   
